-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 12:15:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`user` (
  `User_id` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Latitude` DECIMAL(10,6) NULL,
  `Longitude` DECIMAL(10,6) NULL,
  `AFM` VARCHAR(20) NULL,
  `admin_flag` BIT(1) NULL DEFAULT 0,
  `approved_flag` BIT(1) NULL DEFAULT 0,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`seller` (
  `User_id` VARCHAR(45) NOT NULL,
  `Rating` VARCHAR(45) NULL,
  PRIMARY KEY (`User_id`),
  CONSTRAINT `fk_selller_user`
    FOREIGN KEY (`User_id`)
    REFERENCES `testdb`.`user` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`item` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Currently` DECIMAL(10,2) NULL DEFAULT 0,
  `Last_Bidder` VARCHAR(45) NULL,
  `Buy_Price` DECIMAL(10,2) NULL,
  `First_Bid` DECIMAL(10,2) NULL,
  `Number_of_Bids` INT NULL DEFAULT 0,
  `Started` TIMESTAMP NULL,
  `Ends` TIMESTAMP NULL,
  `Location` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Latitude` DECIMAL(10,6) NULL,
  `Longitude` DECIMAL(10,6) NULL,
  `Description` VARCHAR(1000) NULL,
  `User_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_item_selller1_idx` (`User_id` ASC),
  CONSTRAINT `fk_item_selller`
    FOREIGN KEY (`User_id`)
    REFERENCES `testdb`.`seller` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`bidder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`bidder` (
  `User_id` VARCHAR(45) NOT NULL,
  `Rating` INT NULL,
  `Location` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`User_id`),
  CONSTRAINT `fk_bidder_user`
    FOREIGN KEY (`User_id`)
    REFERENCES `testdb`.`user` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`bid` (
  `User_id` VARCHAR(45) NOT NULL,
  `Time` TIMESTAMP NOT NULL,
  `Amount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`User_id`, `Time`),
  CONSTRAINT `fk_bid_bidder`
    FOREIGN KEY (`User_id`)
    REFERENCES `testdb`.`bidder` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`category` (
  `Category_Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Category_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`item_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`item_has_category` (
  `ItemID` INT NOT NULL,
  `Category_Id` INT NOT NULL,
  PRIMARY KEY (`ItemID`, `Category_Id`),
  INDEX `fk_item_has_category_category1_idx` (`Category_Id` ASC),
  INDEX `fk_item_has_category_item1_idx` (`ItemID` ASC),
  CONSTRAINT `fk_item_has_category_item1`
    FOREIGN KEY (`ItemID`)
    REFERENCES `testdb`.`item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_category_category1`
    FOREIGN KEY (`Category_Id`)
    REFERENCES `testdb`.`category` (`Category_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`item_has_bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`item_has_bid` (
  `ItemID` INT NOT NULL,
  `User_id` VARCHAR(45) NOT NULL,
  `Time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ItemID`, `User_id`, `Time`),
  INDEX `fk_item_has_bid_bid1_idx` (`User_id` ASC, `Time` ASC),
  INDEX `fk_item_has_bid_item1_idx` (`ItemID` ASC),
  CONSTRAINT `fk_item_has_bid_item1`
    FOREIGN KEY (`ItemID`)
    REFERENCES `testdb`.`item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_bid_bid1`
    FOREIGN KEY (`User_id` , `Time`)
    REFERENCES `testdb`.`bid` (`User_id` , `Time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`image` (
  `Image_id` INT NOT NULL AUTO_INCREMENT,
  `Image_path` VARCHAR(200) NULL,
  `ItemID` INT NULL,
  PRIMARY KEY (`Image_id`),
  INDEX `fk_image_item1_idx` (`ItemID` ASC),
  CONSTRAINT `fk_image_item1`
    FOREIGN KEY (`ItemID`)
    REFERENCES `testdb`.`item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Ratings` (
  `ItemID` INT NOT NULL,
  `User_id` VARCHAR(45) NOT NULL,
  `Rating` DECIMAL(3,2) NULL,
  PRIMARY KEY (`ItemID`, `User_id`),
  INDEX `fk_item_has_user_user1_idx` (`User_id` ASC),
  INDEX `fk_item_has_user_item1_idx` (`ItemID` ASC),
  CONSTRAINT `fk_item_has_user_item1`
    FOREIGN KEY (`ItemID`)
    REFERENCES `testdb`.`item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_user_user1`
    FOREIGN KEY (`User_id`)
    REFERENCES `testdb`.`user` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`message` (
  `Message_id` INT NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(45) NULL,
  `Created_at` TIMESTAMP NULL,
  `Read` BIT NULL,
  `ItemID` INT NOT NULL,
  `Sender` VARCHAR(45) NOT NULL,
  `Reicever` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Message_id`),
  INDEX `fk_message_item1_idx` (`ItemID` ASC),
  INDEX `fk_message_user1_idx` (`Sender` ASC),
  INDEX `fk_message_user2_idx` (`Reicever` ASC),
  CONSTRAINT `fk_message_item1`
    FOREIGN KEY (`ItemID`)
    REFERENCES `testdb`.`item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`Sender`)
    REFERENCES `testdb`.`user` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`Reicever`)
    REFERENCES `testdb`.`user` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
